carpooling/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.views.generic.base import RedirectView
from tastypie.api import Api
from region.api import CityResource
from pooling.views import MyLocationListView, MyPoolingListView, IndexView
from member.views import MemberUpdateView

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       )

urlpatterns += patterns('',
                        url(r'^members/', include('member.urls', namespace='member')),
                        url(r'^poolings/', include('pooling.urls', namespace='pooling')), )

urlpatterns += patterns('',
                        url(r'^regions/', include('region.urls', namespace='region')),)

login_urls = patterns('',
                      url(r'^login/', RedirectView.as_view(url='/account/login/')),
                      url(r'^logout/', RedirectView.as_view(url='/account/logout/')),
                      url(r'^signup/', RedirectView.as_view(url='/account/signup/')), )

reset_password_urls = patterns('',
                               url(r'^password_reset/$', password_reset, name='password_reset'),
                               url(r'^password_reset/done/$', password_reset_done, name="password_reset_done"),
                               url(r'^password_reset/confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                                   password_reset_confirm, name="password_reset_confirm"),
                               url(r'^password_reset/complete/$', password_reset_complete, name="password_reset_complete"))

my_locations_urls = patterns('',
                             url(r'^my_locations/$', MyLocationListView.as_view(), name='my_locations'),
                             url(r'^my_poolings/$', MyPoolingListView.as_view(), name='my_poolings'),)

account_urls = patterns('',
                        url(r'^account/', include(my_locations_urls, namespace='account')),
                        url(r'^account/', include('allauth.urls')),
                        url(r'^account/profile/', MemberUpdateView.as_view(), name='account_profile'), )
                        # url(r'^accounts/', include('userena.urls')), )

urlpatterns += login_urls + reset_password_urls + account_urls

api = Api(api_name='v1')
api.register(CityResource())

urlpatterns += patterns('', url(r'^api/', include(api.urls)), ) + \
               patterns('', url(r'^$', IndexView.as_view(), name='index'))

member/urls.py
__author__ = 'yukakami'

from django.conf.urls import patterns, include, url
from tastypie.api import Api

from api import MemberResource, ContactResource
from views import MemberListView, MemberDetailView


v1_api = Api(api_name='v1')
v1_api.register(MemberResource())
v1_api.register(ContactResource())

urlpatterns = patterns('',
                url(r'^api/', include(v1_api.urls)),
                url(r'^list/', MemberListView.as_view(), name='list'),
                url(r'^(?P<slug>[\w-]+)/', MemberDetailView.as_view(), name='detail'),
)

pooling/urls.py
__author__ = 'yukakami'

from django.conf.urls import patterns, url, include
from views import *


location_urls = patterns('',
                         url(r'^new/$', LocationCreateView.as_view(), name='create'),
                         url(r'^update/(?P<pk>[0-9]+)/$', LocationUpdateView.as_view(), name='update'),
                         url(r'^delete/(?P<pk>[0-9]+)/$', LocationDeleteView.as_view(), name='delete'),
                         url(r'^json-detail/(?P<pk>[0-9]+)/$', LocationDetailJsonView.as_view(), name='json-detail'),
                         url(r'^list/$', LocationListView.as_view(), name='list'), )

pooling_urls = patterns('',
                        url(r'^(?P<pk>\d+)/$', PoolingDetailView.as_view(), name='detail'),
                        url(r'^new/$', PoolingCreateView.as_view(), name='create'),
                        url(r'^delete/(?P<pk>[0-9]+)/$', PoolingDeleteView.as_view(), name='delete'),
                        url(r'^search/$', PoolingSearchView.as_view(), name='search'),
                        url(r'^list/$', PoolingListView.as_view(), name='list'),
                        url(r'^json-detail/(?P<pk>[0-9]+)/$', PoolingDetailJsonView.as_view(), name='json-detail'),)

application_urls = patterns('',
                            url(r'^list/$', ApplicationListView.as_view(), name='my_applications'),
                            url(r'^received-detail/(?P<pk>\d+)/$', ApplicationReceivedUpdateView.as_view(), name='received-detail'),
                            url(r'^sent/(?P<pk>\d+)/$', ApplicationSentUpdateView.as_view(), name='sent'),
                            url(r'^received/$', ApplicationReceivedListView.as_view(), name='received_applications'), 
                            url(r'^ongoing/$', ApplicationOnGoingListView.as_view(), name='ongoing_applications'))

urlpatterns = patterns('',
                       url(r'^locations/', include(location_urls, namespace='location')),
                       url(r'^applications/', include(application_urls, namespace='application')),
                       url(r'', include(pooling_urls, namespace='pooling')), )

pooling/models.py
from django.db import models
from django.contrib.gis.db import models as gis_models
from django.utils.translation import ugettext as _
from generic.middleware.threadlocal import get_current_user
import datetime

from region.models import City
from member.models import Member


class LocationType(object):
    HOME = 5
    SCHOOL = 10
    COLLEGE = 15
    JOB = 20
    OTHER = 100

    @classmethod
    def get_choices(cls):
        choices = [
            (cls.HOME, _('home'.capitalize())), (cls.SCHOOL, _('school'.capitalize())),
            (cls.COLLEGE, _('college'.capitalize())), (cls.JOB, _('job'.capitalize())),
            (cls.OTHER, _('other'.capitalize()))
        ]
        return choices

    @classmethod
    def get_name(cls, value):
        if value == cls.HOME:
            name = _('home'.capitalize())
        elif value == cls.SCHOOL:
            name = _('school'.capitalize())
        elif value == cls.COLLEGE:
            name = _('college'.capitalize())
        elif value == cls.JOB:
            name = _('job'.capitalize())
        else:
            name = _('other'.capitalize())
        return name

    @classmethod
    def get_iterable(cls):
        iterable = [cls.HOME, cls.SCHOOL, cls.COLLEGE, cls.JOB, cls.OTHER]
        return iterable


class Location(gis_models.Model):
    name = models.IntegerField(max_length=100, verbose_name=_('location\'s name'), choices=LocationType.get_choices())
    street = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("street"))
    city = models.ForeignKey(City, verbose_name=_("city"))
    lnglat = gis_models.PointField(srid=4326)  # x = lng, y = lat
    description = models.TextField(blank=True, null=True, verbose_name=_('location\'s description'))
    member = models.ForeignKey(Member, default=get_current_user())
    objects = gis_models.GeoManager()

    def __unicode__(self):
        return u"%s: %s - %s" % (self.get_name(), unicode(self.city), self.street or _("no street"))

    @property
    def coordinates(self):
        return '%s, %s' % (str(self.latitude), str(self.longitude))

    @property
    def owner(self):
        return self.member

    @property
    def latitude(self):
        return self.lnglat.get_y()

    @property
    def longitude(self):
        return self.lnglat.get_x()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # self.member = get_current_user()
        super(Location, self).save()

    def get_name(self):
        return LocationType.get_name(self.name)


class PoolingFrequency(object):
    NEVER = 0
    EVERY_DAY = 1
    EVERY_WEEKDAY = 2
    EVERY_WEEKEND = 3
    EVERY_WEEK = 4
    EVERY_MONTH = 5

    @classmethod
    def get_choices(cls):
        choices = [(cls.NEVER, _('--')), (cls.EVERY_DAY, _('every day'.capitalize())),
                   (cls.EVERY_WEEKDAY, _('every weekday'.capitalize())), (cls.EVERY_WEEKEND, _('every weekend'.capitalize())),
                   (cls.EVERY_WEEK, _('every week'.capitalize())), (cls.EVERY_MONTH, _('every month'.capitalize()))]
        return choices

    @classmethod
    def get_name(cls, value):
        name = ''
        if value == cls.NEVER:
            name = _('never')
        elif value == cls.EVERY_DAY:
            name = _('every day'.capitalize())
        elif value == cls.EVERY_WEEKEND:
            name = _('every weekend'.capitalize())
        elif value == cls.EVERY_WEEK:
            name = _('every week'.capitalize())
        elif value == cls.EVERY_MONTH:
            name = _('every month'.capitalize())
        return name


class Pooling(models.Model):
    location_from = models.ForeignKey(Location, related_name='from_set', verbose_name=_("from"))
    location_to = models.ForeignKey(Location, related_name='to_set', verbose_name=_("to"))
    date = models.DateField(verbose_name=_("date"))
    time = models.TimeField(blank=True, null=True, verbose_name=_("time"))
    frequency = models.IntegerField(choices=PoolingFrequency.get_choices(), default=PoolingFrequency.NEVER,
                                    verbose_name=_("frequency"))
    description = models.TextField(blank=True, null=True, verbose_name=_('location\'s description'))
    public = models.BooleanField(blank=True, default=True, verbose_name=_("public"))
    member = models.ForeignKey(Member, default=get_current_user())
    in_need = models.BooleanField(blank=True, default=False, verbose_name=_("in need"),
                                  help_text=_('Indicates if its an offer or demand.'))
    seats = models.IntegerField(verbose_name=_("seats"), help_text=_('Indicates the amount of seats needed or available.'))
    remaining_seats = models.IntegerField()

    def __unicode__(self):
        return '%s - %s' % (unicode(self.location_from.city), unicode(self.location_to.city))

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # self.member = get_current_user()
        if self.remaining_seats is None:
            self.remaining_seats = self.seats
        super(Pooling, self).save()

    @property
    def owner(self):
        return self.member

    def has_seats(self):
        return self.remaining_seats > 0

    def get_repeat(self):
        return PoolingFrequency.get_name(self.frequency)

    def occupy_seat(self, quant=1):
        self.remaining_seats -= quant
        # TODO check whether save needs to be called explicitly
        self.save()

    def release_seat(self, quant=1):
        self.remaining_seats += quant
        # TODO check whether save needs to be called explicitly
        self.save()


class ApplicationStatus(object):
    ACCEPTED = 1
    REJECTED = 5
    PENDING = 10
    CANCELED = 15
    EXPIRED = 20
    DELETED = 100

    @classmethod
    def get_name(cls, value):
        name = ''
        if value == cls.ACCEPTED:
            name = _('accepted'.capitalize())
        elif value == cls.REJECTED:
            name = _('rejected'.capitalize())
        elif value == cls.PENDING:
            name = _('pending'.capitalize())
        elif value == cls.CANCELED:
            name = _('canceled'.capitalize())
        elif value == cls.EXPIRED:
            name = _('expired'.capitalize())
        return name

    @classmethod
    def get_choices(cls):
        choices = [(cls.ACCEPTED, _('accepted').capitalize()), (cls.REJECTED, _('rejected').capitalize()),
                   (cls.PENDING, _('pending'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
                   (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_1_statuses(cls):
        u""" ACCEPTED """
        choices = [cls.ACCEPTED, cls.CANCELED, cls.EXPIRED]
        # choices = [(cls.ACCEPTED, _('accepted').capitalize()), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_5_statuses(cls):
        u""" REJECTED """
        choices = [cls.REJECTED]
        # choices = [(cls.REJECTED, _('rejected'.capitalize()))]
        return choices

    @classmethod
    def next_10_statuses(cls):
        u""" PENDING """
        choices = [cls.PENDING, cls.ACCEPTED, cls.REJECTED, cls.CANCELED, cls.EXPIRED]
        # choices = [(cls.PENDING, _('pending'.capitalize())), (cls.ACCEPTED, _('accepted'.capitalize())),
        #            (cls.REJECTED, _('rejected'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_10_applicant_statuses(cls):
        u""" PENDING, for the applicant """
        choices = [cls.PENDING, cls.CANCELED, cls.EXPIRED]
        # choices = [(cls.PENDING, _('pending'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_10_receiver_statuses(cls):
        u""" PENDING, for the application receiver """
        choices = [cls.PENDING, cls.ACCEPTED, cls.REJECTED, cls.EXPIRED]
        # choices = [(cls.PENDING, _('pending'.capitalize())), (cls.ACCEPTED, _('accepted'.capitalize())),
        #            (cls.REJECTED, _('rejected'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_15_statuses(cls):
        u""" CANCELED """
        choices = [cls.CANCELED]
        # choices = [(cls.CANCELED, _('canceled'.capitalize()))]
        return choices

    @classmethod
    def next_20_statuses(cls):
        u""" EXPIRED """
        choices = [cls.EXPIRED]
        # choices = [(cls.EXPIRED, _('expired'.capitalize()))]
        return choices


class Application(models.Model):
    member = models.ForeignKey(Member)
    pooling = models.ForeignKey(Pooling)
    seats = models.IntegerField(verbose_name=_("seats"))
    status = models.IntegerField(verbose_name=_("status"), choices=ApplicationStatus.get_choices(),
                                 default=ApplicationStatus.PENDING)
    status_statistic = models.IntegerField(choices=ApplicationStatus.get_choices(), null=True, blank=True)
    creation_date = models.DateTimeField(default=datetime.datetime.now(), verbose_name=_("creation date"))
    last_status_change = models.DateTimeField(default=datetime.datetime.now(), verbose_name=_("last status change"))
    description = models.TextField(blank=True, null=True, verbose_name=_("description"))

    _status = None

    class Meta:
        ordering = ['last_status_change', 'creation_date']

    def __init__(self, *args, **kwargs):
        super(Application, self).__init__(*args, **kwargs)
        self._status = self.status

    def __unicode__(self):
        return u"Pooling ID: %d, Pooler: %s, Applicant: %s" % (self.pooling.id, self.pooling.member, self.member)

    @property
    def owner(self):

pooling/templates/pooling/application_detail_form.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ block.super }}{% trans "location"|capfirst %}{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/google_map.css' %}">
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCwq9RrbRX2zxh9BnahOtXWuj8ATCoMEpg&sensor=true">
    </script>
    <link rel="stylesheet" href="{% static 'carpooling/css/cities.css' %}">
{% endblock %}

{% block content_title %}{% trans "application"|capfirst %}{% endblock content_title %}
{% block content_subtitle %}{% endblock content_subtitle %}

{% block body_attributes %}
    data-ng-app="Carpooling"
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td colspan="2" style="margin: auto;">
                                {% comment %}<img src="{{ user.photo }}" />{% endcomment %}
                                <img src="http://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50" />
                            </td>
                        </tr>
                        <tr>
                            <td>{% trans 'username'|capfirst %}</td>
                            <td>
                                <a href="{% url 'member:detail' application.member.username %}" title="{% trans "view profile" %}">
                                    {{ application.member.username }}
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>{% trans 'full name'|capfirst %}</td>
                            <td>{{ application.member.full_name }}</td>
                        </tr>
                        {% if application.member.public_gender %}
                            <tr>
                                <td>{% trans 'gender'|capfirst %}</td>
                                <td>{{ application.member.get_gender }}</td>
                            </tr>
                        {% endif %}
                        {% if application.member.public_birthdate %}
                            <tr>
                                <td>{% trans 'birthdate'|capfirst %}</td>
                                <td>{{ application.member.birthdate }}</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <form action="." method="post">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <td>{% trans 'id'|upper %}</td>
                                <td>{{ application.id }}</td>
                            </tr>
                            <tr>
                                <td>{% trans 'creation'|capfirst%}</td>
                                <td>{{ application.creation_date }}</td>
                            </tr>
                            <tr>
                                <td>{% trans 'pooling'|capfirst %}</td>
                                <td>
                                    {% trans 'from'|capfirst %}: {{ application.pooling.location_from }}<br />
                                    {% trans 'to'|capfirst %}: {{ application.pooling.location_to }}
                                </td>
                            </tr>
                            <tr>
                                <td>{% trans 'description'|capfirst %}</td>
                                <td>{{ application.description|default:'-' }}</td>
                            </tr>
                            <tr>
                                <td>
                                    {% if application.pooling.in_need %}
                                        {% trans 'offers'|capfirst %}
                                    {% else %}
                                        {% trans 'requires'|capfirst %}
                                    {% endif %}
                                </td>
                                <td>{{ application.seats }}</td>
                            </tr>
                            <tr>
                                <td>{% trans 'status'|capfirst %}</td>
                                <td>
                                    {% if form.status %}
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{ form.status|add_class:'form-control' }}
                                        </div>
                                        <div style="display: none;">
                                            {% for field in form.hidden_fields %}
                                                {{ field }}
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ application.get_status }}
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    {% if object.end_flow %}
                        <a href="{% url 'pooling:application:received_applications' %}" class="btn btn-danger">
                            <i class="fa fa-arrow-circle-o-left"></i> {% trans "go back"|title %}
                        </a>
                    {% else %}
                        <button type="submit" class="btn btn-success">
                            {% trans "save"|capfirst %}
                        </button>
                        <a href="{% url 'pooling:application:received_applications' %}" class="btn btn-danger">{% trans "cancel"|title %}</a>
                    {% endif %}
                </form>
            </div>
        </div>
{#        <div class="col-lg-6">#}
{#            <div id="div_map_canvas"></div>#}
{#        </div>#}
    </div>

{% endblock content %}
{% block scripts %}
{#    <script type="text/javascript" src="{% static 'libs/js/angular/angular.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'libs/js/angular/angular-route.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'libs/js/angular/angular-animate.min.js' %}"></script>#}
{#    <script>#}
{#        angular.module('Carpooling', ['ngRoute']);#}
{#    </script>#}
{#    <script type="text/javascript" src="{% static 'js/google_map_2.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'libs/js/jquery.autocomplete.js' %}"></script>
    <script type="text/javascript" src="{% static 'carpooling/js/cities.js' %}"></script>
{% endblock scripts %}

pooling/templates/pooling/pooling_detail.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ block.super }}{% trans "location"|capfirst %}{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/google_map.css' %}">
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCwq9RrbRX2zxh9BnahOtXWuj8ATCoMEpg&sensor=true">
    </script>
    <link rel="stylesheet" href="{% static 'carpooling/css/cities.css' %}">
{% endblock %}

{% block content_title %}{% trans "pooling"|capfirst %}{% endblock content_title %}
{% block content_subtitle %}{% endblock content_subtitle %}

{% block content %}
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td colspan="2" style="margin: auto;">
                                {% comment %}<img src="{{ user.photo }}" />{% endcomment %}
                                <img src="http://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50" />
                            </td>
                        </tr>
                        <tr>
                            <td>{% trans 'username'|capfirst %}</td>
                            <td>
                                <a href="{% url 'member:detail' object.member.username %}" title="{% trans "view profile" %}">
                                    {{ object.member.username }}
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>{% trans 'full name'|capfirst %}</td>
                            <td>{{ object.member.full_name }}</td>
                        </tr>
                        {% if object.member.public_gender %}
                            <tr>
                                <td>{% trans 'gender'|capfirst %}</td>
                                <td>{{ object.member.get_gender }}</td>
                            </tr>
                        {% endif %}
                        {% if object.member.public_birthdate %}
                            <tr>
                                <td>{% trans 'birthdate'|capfirst %}</td>
                                <td>{{ object.member.birthdate }}</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td>{% trans 'id'|upper %}</td>
                            <td>{{ object.id }}</td>
                        </tr>
                        <tr>
                            <td>{% trans 'from'|capfirst %}</td>
                            <td id="id_location_from" data-value="{{ object.location_from.id }}">{{ object.location_from }}</td>
                        <tr>
                            <td>{% trans 'to'|capfirst %}</td>
                            <td id="id_location_to" data-value="{{ object.location_to.id }}">{{ object.location_to }}</td>
                        </tr>
                        <tr>
                            <td>{% trans 'date'|capfirst %}</td>
                            <td>
                                {{ object.date }}
                                {% if object.time %}, {{ object.time }}{% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>{% trans 'frequency'|capfirst %}</td>
                            <td>{{ object.get_repeat }}</td>
                        </tr>
                        <tr>
                            <td>{% trans 'description'|capfirst %}</td>
                            <td>{{ object.description|default:'-' }}</td>
                        </tr>
                        <tr>
                            <td>
                                {% if object.in_need %}
                                    {% trans 'need'|capfirst %}
                                {% else %}
                                    {% trans 'available'|capfirst %}
                                {% endif %}
                            </td>
                            <td>
                                {% if object.in_need %}
                                    {{ object.seats }}
                                {% else %}
                                    {{ object.remaining_seats }} / {{ object.seats }}
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-6">
            <div id="div_map_canvas"></div>
        </div>
    </div>
    <div class="row" {# data-ng-controller="CarpoolingApplyController" #}>
{% comment %}        <div class="col-lg-6" {# data-ng-show="showApplicationForm" data-ng-init="showApplicationForm = true" #}>
            <button type="button" class="btn btn-success" data-ng-click="showApplicationForm = !showApplicationForm">
                <i class="fa fa-check-square-o"></i> {% trans "apply"|capfirst %}
            </button>
            <a href="{% url 'pooling:pooling:list' %}" class="btn btn-danger">{% trans "go back"|title %}</a>
        </div>
{% endcomment %}
        {% if form %}
            <div {# data-ng-hide="showApplicationForm" #}>
                <div class="col-lg-4"></div>
                <form action="." method="post">
                    <div class="col-lg-4">
                        {% csrf_token %}
                        {% for field in form.hidden_fields %}
                            {{ field }}
                        {% endfor %}
                        {% for field in form.visible_fields %}
                            <div class="form-group {% if field.errors %}has-error{% endif %}">
                                <label for="{{ field.id_for_field }}" class="control-label">
                                    {{ field.label }}{% if field.field.required %} *{% endif %}
                                </label>
                                {{ field|add_class:'form-control' }}
                                {% if field.errors %}
                                    <div class="help-block errornote">{{ field.errors }}</div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-success">
                            {% trans "save"|capfirst %}
                        </button>
                        <a href="{% url 'pooling:pooling:list' %}" class="btn btn-danger">{% trans "cancel"|title %}</a>
                    </div>
                </form>
                <div class="col-lg-4"></div>
            </div>
        {% elif pooling.member != user %}
            <div class="alert alert-warning">
                {% if pooling.remaining_seats == 0 %}
                    {% trans "there are no seats available for this pooling"|capfirst %}.
                {% else %}
                    {% trans "you have already applied for this pooling. check the following link"|capfirst %}
                    <a href="{% url 'pooling:application:ongoing_applications' %}">{% trans "ongoing poolings" %}</a>
                {% endif %}
            </div>
        {% endif %}
    </div>

{% endblock content %}
{% block scripts %}
{% comment %}     <script type="text/javascript" src="{% static 'libs/js/angular/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/js/angular/angular-route.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/js/angular/angular-animate.min.js' %}"></script>
    <script>
        angular.module('Carpooling', ['ngRoute']);
    </script>{% endcomment %}
    <script type="text/javascript" src="{% static 'js/google_map_2.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/js/jquery.autocomplete.js' %}"></script>
    <script type="text/javascript" src="{% static 'carpooling/js/cities.js' %}"></script>
{% endblock scripts %}