carpooling/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.views.generic.base import RedirectView
from tastypie.api import Api
from region.api import CityResource
from pooling.views import MyLocationListView, MyPoolingListView, IndexView
from member.views import MemberUpdateView

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       )

urlpatterns += patterns('',
                        url(r'^members/', include('member.urls', namespace='member')),
                        url(r'^poolings/', include('pooling.urls', namespace='pooling')), )

urlpatterns += patterns('',
                        url(r'^regions/', include('region.urls', namespace='region')),)

login_urls = patterns('',
                      url(r'^login/', RedirectView.as_view(url='/account/login/')),
                      url(r'^logout/', RedirectView.as_view(url='/account/logout/')),
                      url(r'^signup/', RedirectView.as_view(url='/account/signup/')), )

reset_password_urls = patterns('',
                               url(r'^password_reset/$', password_reset, name='password_reset'),
                               url(r'^password_reset/done/$', password_reset_done, name="password_reset_done"),
                               url(r'^password_reset/confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                                   password_reset_confirm, name="password_reset_confirm"),
                               url(r'^password_reset/complete/$', password_reset_complete, name="password_reset_complete"))

my_locations_urls = patterns('',
                             url(r'^my_locations/$', MyLocationListView.as_view(), name='my_locations'),
                             url(r'^my_poolings/$', MyPoolingListView.as_view(), name='my_poolings'),)

account_urls = patterns('',
                        url(r'^account/', include(my_locations_urls, namespace='account')),
                        url(r'^account/', include('allauth.urls')),
                        url(r'^account/profile/', MemberUpdateView.as_view(), name='account_profile'), )
                        # url(r'^accounts/', include('userena.urls')), )

urlpatterns += login_urls + reset_password_urls + account_urls

api = Api(api_name='v1')
api.register(CityResource())

urlpatterns += patterns('', url(r'^api/', include(api.urls)), ) + \
               patterns('', url(r'^$', IndexView.as_view(), name='index'))

member/urls.py
__author__ = 'yukakami'

from django.conf.urls import patterns, include, url
from tastypie.api import Api

from api import MemberResource, ContactResource
from views import MemberListView, MemberDetailView


v1_api = Api(api_name='v1')
v1_api.register(MemberResource())
v1_api.register(ContactResource())

urlpatterns = patterns('',
                url(r'^api/', include(v1_api.urls)),
                url(r'^list/', MemberListView.as_view(), name='list'),
                url(r'^(?P<slug>[\w-]+)/', MemberDetailView.as_view(), name='detail'),
)

carpooling/templates/includes/libs_chart.html
{% load static %}

<script src="{% static 'admin/js/plugins/flot/excanvas.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'admin/js/plugins/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'admin/js/plugins/flot/jquery.flot.resize.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>

carpooling/templates/includes/notification_client.html
{#{% load static %}#}
{#<script src="http://{{ node_host }}:{{ node_port }}/socket.io/socket.io.js"></script>#}
{#<script>#}
{#    $(document).ready(function() {#}
{#        var socket = io.connect("{{ node_host }}", {port: {{ node_port }}});#}
{##}
{#        socket.on('connect', function() {#}
{#            console.log('connected');#}
{#        });#}
{#        socket.on('notify_{{ user.id }}', function(data) {#}
{#            data = JSON.parse(data);#}
{#            var alert_color = '';#}
{#            if (data.status == 'accepted')#}
{#                alert_color = 'alert-success';#}
{#            else if (data.status == 'pending')#}
{#                alert_color = 'alert-warning';#}
{#            else if (data.status == 'end')#}
{#                alert_color = 'alert-danger';#}
{#            var html =#}
{#                        '<li class="'+alert_color+'">' +#}
{#                        '<a href="#"><div>{#<strong>John Smith</strong><span class="pull-right text-muted">' +#}
{#                        '<em>' + data.datetime + '</em>' +#}
{#                        '</span></div>' +#}
{#                        '<div>' + data.message + '</div>' +#}
{#                        '</a></li><li class="divider"></li>';#}
{##}
{#            $('#id_notifications').prepend(html);#}
{#            var notifications_counter = $('#id_notifications li').length / 2;#}
{#            $('.notification_counter').html(notifications_counter);#}
{#            var title = document.title;#}
{#            title = title.replace(new RegExp("\\([0-9]+\\)"), "");#}
{#            document.title = "(" + notifications_counter + ") " + title;#}
{#            if ("vibrate" in navigator) {#}
{#                navigator.vibrate(1000);#}
{#                console.log("vibro");#}
{#            } else console.log("no vibro");#}
{#        });#}
{#    });#}
{#</script>#}

carpooling/templates/includes/paging.html
<ul class="pagination">
    {% if page_obj.number == 1 %}
        <li class="disabled"><a href="#">&laquo;</a></li>
    {% else %}
        <li><a href="?page=1">&laquo;</a></li>
    {% endif %}
    {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
    {% endif %}
    <li class="active"><a href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a></li>
    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
    {% endif %}
    {% if page_obj.number == paginator.num_pages %}
        <li class="disabled"><a href="#">&raquo;</a></li>
    {% else %}
        <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
    {% endif %}
</ul>

carpooling/templates/includes/top_navbar.html
{% load i18n %}

<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">Arg-Pooling</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i> <span class="badge badge-danger notification_counter"></span> <i class="fa fa-caret-down"></i>
                </a>
                <ul id="id_notifications" class="dropdown-menu dropdown-messages">
{#                    <span class="pull-left text-muted">#}
{#                        <em>{% trans 'there are no new notifications' %}</em>#}
{#                    </span>#}
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="{% url 'pooling:application:my_applications' %}">
                            <div>
                                <i class="fa fa-mail-reply fa-fw"></i> {% trans 'sent applications'|capfirst %}
                                <span class="badge badge-info">{{ pending_counter }}</span><span class="text-muted small"> pending</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="{% url 'pooling:application:received_applications' %}">
                            <div>
                                <i class="fa fa-mail-forward fa-fw"></i> {% trans 'received applications'|capfirst %}
                                <span class="badge badge-warning">{{ received_counter }}</span><span class="text-muted small"> pending</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="{% url 'pooling:application:ongoing_applications' %}">
                            <div>
                                <i class="fa fa-truck fa-fw"></i> {% trans 'on going'|capfirst %}
                                <span class="badge badge-success">{{ ongoing_counter }}</span>
                            </div>
                        </a>
                    </li>
                </ul><!-- /.dropdown-alerts -->
            </li><!-- /.dropdown -->

            <li class="dropdown user-dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>
                    {% if user.full_name %}
                        {{ user.full_name }}
                    {% else %}
                        {{ user.username }}
                    {% endif %}
                    <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'account_profile' %}"><i class="fa fa-user fa-fw"></i> {% trans 'profile'|capfirst %}</a></li>
                    <li><a href="{% url 'account_change_password' %}"><i class="fa fa-lock fa-fw"></i> {% trans 'change password'|capfirst %}</a></li>
                    <li><a href="{% url 'account:my_locations' %}"><i class="fa fa-map-marker"></i> {% trans 'My locations' %}</a></li>
                    <li><a href="{% url 'account:my_poolings' %}"><i class="fa fa-map-marker"></i> {% trans 'My poolings' %}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> {% trans 'log out'|title %}</a></li>
                </ul><!-- /.dropdown-user -->
            </li><!-- /.dropdown -->
        {% else %}
            <li><a href="{% url 'account_login' %}">{% trans "log in"|title %}</a></li>
            <li><a href="{% url 'account_signup' %}">{% trans "sign up"|title %}</a></li>
        {% endif %}
    </ul><!-- /.navbar-top-links -->
</nav><!-- /.navbar-static-top -->