carpooling/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.views.generic.base import RedirectView
from tastypie.api import Api
from region.api import CityResource
from pooling.views import MyLocationListView, MyPoolingListView, IndexView
from member.views import MemberUpdateView

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       )

urlpatterns += patterns('',
                        url(r'^members/', include('member.urls', namespace='member')),
                        url(r'^poolings/', include('pooling.urls', namespace='pooling')), )

urlpatterns += patterns('',
                        url(r'^regions/', include('region.urls', namespace='region')),)

login_urls = patterns('',
                      url(r'^login/', RedirectView.as_view(url='/account/login/')),
                      url(r'^logout/', RedirectView.as_view(url='/account/logout/')),
                      url(r'^signup/', RedirectView.as_view(url='/account/signup/')), )

reset_password_urls = patterns('',
                               url(r'^password_reset/$', password_reset, name='password_reset'),
                               url(r'^password_reset/done/$', password_reset_done, name="password_reset_done"),
                               url(r'^password_reset/confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                                   password_reset_confirm, name="password_reset_confirm"),
                               url(r'^password_reset/complete/$', password_reset_complete, name="password_reset_complete"))

my_locations_urls = patterns('',
                             url(r'^my_locations/$', MyLocationListView.as_view(), name='my_locations'),
                             url(r'^my_poolings/$', MyPoolingListView.as_view(), name='my_poolings'),)

account_urls = patterns('',
                        url(r'^account/', include(my_locations_urls, namespace='account')),
                        url(r'^account/', include('allauth.urls')),
                        url(r'^account/profile/', MemberUpdateView.as_view(), name='account_profile'), )
                        # url(r'^accounts/', include('userena.urls')), )

urlpatterns += login_urls + reset_password_urls + account_urls

api = Api(api_name='v1')
api.register(CityResource())

urlpatterns += patterns('', url(r'^api/', include(api.urls)), ) + \
               patterns('', url(r'^$', IndexView.as_view(), name='index'))

member/urls.py
__author__ = 'yukakami'

from django.conf.urls import patterns, include, url
from tastypie.api import Api

from api import MemberResource, ContactResource
from views import MemberListView, MemberDetailView


v1_api = Api(api_name='v1')
v1_api.register(MemberResource())
v1_api.register(ContactResource())

urlpatterns = patterns('',
                url(r'^api/', include(v1_api.urls)),
                url(r'^list/', MemberListView.as_view(), name='list'),
                url(r'^(?P<slug>[\w-]+)/', MemberDetailView.as_view(), name='detail'),
)

pooling/models.py
from django.db import models
from django.contrib.gis.db import models as gis_models
from django.utils.translation import ugettext as _
from generic.middleware.threadlocal import get_current_user
import datetime

from region.models import City
from member.models import Member


class LocationType(object):
    HOME = 5
    SCHOOL = 10
    COLLEGE = 15
    JOB = 20
    OTHER = 100

    @classmethod
    def get_choices(cls):
        choices = [
            (cls.HOME, _('home'.capitalize())), (cls.SCHOOL, _('school'.capitalize())),
            (cls.COLLEGE, _('college'.capitalize())), (cls.JOB, _('job'.capitalize())),
            (cls.OTHER, _('other'.capitalize()))
        ]
        return choices

    @classmethod
    def get_name(cls, value):
        if value == cls.HOME:
            name = _('home'.capitalize())
        elif value == cls.SCHOOL:
            name = _('school'.capitalize())
        elif value == cls.COLLEGE:
            name = _('college'.capitalize())
        elif value == cls.JOB:
            name = _('job'.capitalize())
        else:
            name = _('other'.capitalize())
        return name

    @classmethod
    def get_iterable(cls):
        iterable = [cls.HOME, cls.SCHOOL, cls.COLLEGE, cls.JOB, cls.OTHER]
        return iterable


class Location(gis_models.Model):
    name = models.IntegerField(max_length=100, verbose_name=_('location\'s name'), choices=LocationType.get_choices())
    street = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("street"))
    city = models.ForeignKey(City, verbose_name=_("city"))
    lnglat = gis_models.PointField(srid=4326)  # x = lng, y = lat
    description = models.TextField(blank=True, null=True, verbose_name=_('location\'s description'))
    member = models.ForeignKey(Member, default=get_current_user())
    objects = gis_models.GeoManager()

    def __unicode__(self):
        return u"%s: %s - %s" % (self.get_name(), unicode(self.city), self.street or _("no street"))

    @property
    def coordinates(self):
        return '%s, %s' % (str(self.latitude), str(self.longitude))

    @property
    def owner(self):
        return self.member

    @property
    def latitude(self):
        return self.lnglat.get_y()

    @property
    def longitude(self):
        return self.lnglat.get_x()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # self.member = get_current_user()
        super(Location, self).save()

    def get_name(self):
        return LocationType.get_name(self.name)


class PoolingFrequency(object):
    NEVER = 0
    EVERY_DAY = 1
    EVERY_WEEKDAY = 2
    EVERY_WEEKEND = 3
    EVERY_WEEK = 4
    EVERY_MONTH = 5

    @classmethod
    def get_choices(cls):
        choices = [(cls.NEVER, _('--')), (cls.EVERY_DAY, _('every day'.capitalize())),
                   (cls.EVERY_WEEKDAY, _('every weekday'.capitalize())), (cls.EVERY_WEEKEND, _('every weekend'.capitalize())),
                   (cls.EVERY_WEEK, _('every week'.capitalize())), (cls.EVERY_MONTH, _('every month'.capitalize()))]
        return choices

    @classmethod
    def get_name(cls, value):
        name = ''
        if value == cls.NEVER:
            name = _('never')
        elif value == cls.EVERY_DAY:
            name = _('every day'.capitalize())
        elif value == cls.EVERY_WEEKEND:
            name = _('every weekend'.capitalize())
        elif value == cls.EVERY_WEEK:
            name = _('every week'.capitalize())
        elif value == cls.EVERY_MONTH:
            name = _('every month'.capitalize())
        return name


class Pooling(models.Model):
    location_from = models.ForeignKey(Location, related_name='from_set', verbose_name=_("from"))
    location_to = models.ForeignKey(Location, related_name='to_set', verbose_name=_("to"))
    date = models.DateField(verbose_name=_("date"))
    time = models.TimeField(blank=True, null=True, verbose_name=_("time"))
    frequency = models.IntegerField(choices=PoolingFrequency.get_choices(), default=PoolingFrequency.NEVER,
                                    verbose_name=_("frequency"))
    description = models.TextField(blank=True, null=True, verbose_name=_('location\'s description'))
    public = models.BooleanField(blank=True, default=True, verbose_name=_("public"))
    member = models.ForeignKey(Member, default=get_current_user())
    in_need = models.BooleanField(blank=True, default=False, verbose_name=_("in need"),
                                  help_text=_('Indicates if its an offer or demand.'))
    seats = models.IntegerField(verbose_name=_("seats"), help_text=_('Indicates the amount of seats needed or available.'))
    remaining_seats = models.IntegerField()

    def __unicode__(self):
        return '%s - %s' % (unicode(self.location_from.city), unicode(self.location_to.city))

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # self.member = get_current_user()
        if self.remaining_seats is None:
            self.remaining_seats = self.seats
        super(Pooling, self).save()

    @property
    def owner(self):
        return self.member

    def has_seats(self):
        return self.remaining_seats > 0

    def get_repeat(self):
        return PoolingFrequency.get_name(self.frequency)

    def occupy_seat(self, quant=1):
        self.remaining_seats -= quant
        # TODO check whether save needs to be called explicitly
        self.save()

    def release_seat(self, quant=1):
        self.remaining_seats += quant
        # TODO check whether save needs to be called explicitly
        self.save()


class ApplicationStatus(object):
    ACCEPTED = 1
    REJECTED = 5
    PENDING = 10
    CANCELED = 15
    EXPIRED = 20
    DELETED = 100

    @classmethod
    def get_name(cls, value):
        name = ''
        if value == cls.ACCEPTED:
            name = _('accepted'.capitalize())
        elif value == cls.REJECTED:
            name = _('rejected'.capitalize())
        elif value == cls.PENDING:
            name = _('pending'.capitalize())
        elif value == cls.CANCELED:
            name = _('canceled'.capitalize())
        elif value == cls.EXPIRED:
            name = _('expired'.capitalize())
        return name

    @classmethod
    def get_choices(cls):
        choices = [(cls.ACCEPTED, _('accepted').capitalize()), (cls.REJECTED, _('rejected').capitalize()),
                   (cls.PENDING, _('pending'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
                   (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_1_statuses(cls):
        u""" ACCEPTED """
        choices = [cls.ACCEPTED, cls.CANCELED, cls.EXPIRED]
        # choices = [(cls.ACCEPTED, _('accepted').capitalize()), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_5_statuses(cls):
        u""" REJECTED """
        choices = [cls.REJECTED]
        # choices = [(cls.REJECTED, _('rejected'.capitalize()))]
        return choices

    @classmethod
    def next_10_statuses(cls):
        u""" PENDING """
        choices = [cls.PENDING, cls.ACCEPTED, cls.REJECTED, cls.CANCELED, cls.EXPIRED]
        # choices = [(cls.PENDING, _('pending'.capitalize())), (cls.ACCEPTED, _('accepted'.capitalize())),
        #            (cls.REJECTED, _('rejected'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_10_applicant_statuses(cls):
        u""" PENDING, for the applicant """
        choices = [cls.PENDING, cls.CANCELED, cls.EXPIRED]
        # choices = [(cls.PENDING, _('pending'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_10_receiver_statuses(cls):
        u""" PENDING, for the application receiver """
        choices = [cls.PENDING, cls.ACCEPTED, cls.REJECTED, cls.EXPIRED]
        # choices = [(cls.PENDING, _('pending'.capitalize())), (cls.ACCEPTED, _('accepted'.capitalize())),
        #            (cls.REJECTED, _('rejected'.capitalize())), (cls.CANCELED, _('canceled'.capitalize())),
        #            (cls.EXPIRED, _('expired'.capitalize()))]
        return choices

    @classmethod
    def next_15_statuses(cls):
        u""" CANCELED """
        choices = [cls.CANCELED]
        # choices = [(cls.CANCELED, _('canceled'.capitalize()))]
        return choices

    @classmethod
    def next_20_statuses(cls):
        u""" EXPIRED """
        choices = [cls.EXPIRED]
        # choices = [(cls.EXPIRED, _('expired'.capitalize()))]
        return choices


class Application(models.Model):
    member = models.ForeignKey(Member)
    pooling = models.ForeignKey(Pooling)
    seats = models.IntegerField(verbose_name=_("seats"))
    status = models.IntegerField(verbose_name=_("status"), choices=ApplicationStatus.get_choices(),
                                 default=ApplicationStatus.PENDING)
    status_statistic = models.IntegerField(choices=ApplicationStatus.get_choices(), null=True, blank=True)
    creation_date = models.DateTimeField(default=datetime.datetime.now(), verbose_name=_("creation date"))
    last_status_change = models.DateTimeField(default=datetime.datetime.now(), verbose_name=_("last status change"))
    description = models.TextField(blank=True, null=True, verbose_name=_("description"))

    _status = None

    class Meta:
        ordering = ['last_status_change', 'creation_date']

    def __init__(self, *args, **kwargs):
        super(Application, self).__init__(*args, **kwargs)
        self._status = self.status

    def __unicode__(self):
        return u"Pooling ID: %d, Pooler: %s, Applicant: %s" % (self.pooling.id, self.pooling.member, self.member)

    @property
    def owner(self):

member/forms.py
from django.contrib.auth import get_user_model
from django import forms
from models import Member
from generic import widgets


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    account_field_names = ('username', 'email', 'password1', 'password2')
    personal_field_names = ('first_name', 'last_name', 'gender', 'birthdate')

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'gender', 'birthdate', 'username', 'email', 'password1', 'password2')
        widgets = {'birthdate': widgets.DateWidget}

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

    def signup(self, request, user):
        user.save()


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Member
        exclude = ('is_staff', 'is_active', 'is_superuser', 'date_joined', 'last_login', 'groups',
                   'user_permissions', 'username', 'password')
        widgets = {'birthdate': widgets.DateWidget}

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name', '')
        return first_name.title()

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name', '')
        return last_name.title()

member/views.py
from django.views.generic import ListView, UpdateView, DetailView
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db.models import Q
from django.utils.translation import ugettext as _
from models import Member
from forms import ProfileForm
from generic.views import LoginRequiredView
from pooling.models import Application, ApplicationStatus


class MemberListView(LoginRequiredView, ListView):
    model = Member
    context_object_name = 'member_list'
    paginate_by = getattr(settings, 'PAGINATE_BY', 20)


class MemberDetailView(LoginRequiredView, DetailView):
    model = Member

    def get_context_data(self, **kwargs):
        user = self.object
        context_data = super(MemberDetailView, self).get_context_data(**kwargs)
        sent_application_count = Application.objects.filter(member=user).count()
        received_application_count = Application.objects.filter(pooling__member=user).count()
        sent_received_applications = Application.objects.filter(Q(pooling__member=user) | Q(member=user))
        context_data['sent_application_count'] = sent_application_count
        context_data['received_application_count'] = received_application_count
        context_data['total_application_count'] = received_application_count + sent_application_count
        context_data['accepted_application_count'] = sent_received_applications.filter(status_statistic=ApplicationStatus.ACCEPTED).count()
        context_data['rejected_application_count'] = sent_received_applications.filter(status_statistic=ApplicationStatus.REJECTED).count()
        context_data['canceled_application_count'] = sent_received_applications.filter(status_statistic=ApplicationStatus.CANCELED).count()
        context_data['expired_application_count'] = sent_received_applications.filter(status_statistic=ApplicationStatus.EXPIRED).count()
        context_data['pending_application_count'] = sent_received_applications.filter(status_statistic=ApplicationStatus.PENDING).count()
        return context_data


class MemberUpdateView(LoginRequiredView, UpdateView):
    model = Member
    form_class = ProfileForm
    template_name = 'member/profile_form.html'

    def get_object(self, queryset=None):
        username = self.request.user.username
        return Member.objects.get(username=username)

    def get_success_url(self):
        return reverse('account_profile')

    def form_valid(self, form):
        messages.add_message(self.request, messages.constants.SUCCESS, _(u"your profile was updated successfully"))
        return super(MemberUpdateView, self).form_valid(form)

member/templates/member/member_form.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ block.super }}{% trans "member"|capfirst %}{% endblock title %}

{% block content_title %}{% trans "new member"|title %}{% endblock content_title %}
{% block content_subtitle %}{% endblock content_subtitle %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <form method="post" action=".">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <label class="control-label" for="{{ field.id_for_label }}">
                            {{ field.label }}{% if field.field.required %} *{% endif %}
                        </label>
                        {{ field|add_class:'form-control' }}
                        {% if field.help_text %}
                            <span class="help-block">{{ field.help_text }}</span>
                        {% endif %}
                        {% if field.errors %}
                            <div class="help-block errornote">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-info">{% trans "save"|capfirst %}</button>
                <a href="{% url 'member:list' %}" class="btn btn-danger">{% trans "cancel"|capfirst %}</a>
            </form>
        </div>
    </div>
{% endblock content %}

member/templates/member/member_list.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Members' list" %}{% endblock title %}

{% block content_title %}{% trans "Members' list" %}{% endblock content_title %}
{% block content_subtitle %}{% endblock content_subtitle %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h2>Bordered Table</h2>
            {% if member_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped tablesorter">
                        <thead>
                            <tr>
                                <th># <i class="fa fa-sort"></i></th>
                                <th>{% trans "username"|capfirst %} <i class="fa fa-sort"></i></th>
                                <th>{% trans "full name"|capfirst %} <i class="fa fa-sort"></i></th>
                                <th>{% trans "poolings"|capfirst %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for member in member_list %}
                                <tr>
                                    <td>{{ member.id }}</td>
                                    <td>
                                        <a href="{% url 'member:detail' member.username %}" title="{% trans "view profile" %}">
                                            {{ member.username }}
                                        </a>
                                    </td>
                                    <td>{{ member.get_full_name|default:'' }}</td>
                                    <td class="text-center">{{ member.pooling_set.count }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    {% include 'includes/paging.html' %}
                {% endif %}
            {% else %}
                <div class="alert alert-info alert-dismissable">
                    {% trans 'there are no elements to show.'|capfirst %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

member/templates/member/profile_form.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ block.super }}{% trans "member"|capfirst %}{% endblock title %}

{% block content_title %}{% trans "my profile"|title %}{% endblock content_title %}
{% block content_subtitle %}{% endblock content_subtitle %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message|capfirst }}
                    </div>
                {% endfor %}
            {% endif %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.errors }}
                </div>
            {% endif %}
            <form method="post" action=".">
                {% csrf_token %}
{#                <div class="form-group {% if form.username.errors %}has-error{% endif %}">#}
{#                    <label class="control-label" for="{{ form.username.id_for_label }}">#}
{#                        {{ form.username.label }}#}
{#                    </label>#}
{#                    {{ form.username|add_class:'form-control' }}#}
{#                </div>#}
                <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                    <label class="control-label" for="{{ form.first_name.id_for_label }}">
                        {{ form.first_name.label }}{% if form.first_name.field.required %} *{% endif %}
                    </label>
                    {{ form.first_name|add_class:'form-control' }}
                    {% if form.first_name.help_text %}
                        <span class="help-block">{{ form.first_name.help_text|capfirst }}</span>
                    {% endif %}
                    {% if form.first_name.errors %}
                        <div class="help-block errornote">{{ form.first_name.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                    <label class="control-label" for="{{ form.last_name.id_for_label }}">
                        {{ form.last_name.label }}{% if form.last_name.field.required %} *{% endif %}
                    </label>
                    {{ form.last_name|add_class:'form-control' }}
                    {% if form.last_name.help_text %}
                        <span class="help-block">{{ form.last_name.help_text|capfirst }}</span>
                    {% endif %}
                    {% if form.last_name.errors %}
                        <div class="help-block errornote">{{ form.last_name.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                    <label class="control-label" for="{{ form.email.id_for_label }}">
                        {{ form.email.label }}{% if form.email.field.required %} *{% endif %}
                    </label>
                    {{ form.email|add_class:'form-control' }}
                    {% if form.email.help_text %}
                        <span class="help-block">{{ form.email.help_text|capfirst }}</span>
                    {% endif %}
                    {% if form.email.errors %}
                        <div class="help-block errornote">{{ form.email.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group {% if form.birthdate.errors %}has-error{% endif %}">
                    <label class="control-label" for="{{ form.last_name.id_for_label }}">
                        {{ form.birthdate.label }}{% if form.birthdate.field.required %} *{% endif %}
                    </label>
                    {{ form.birthdate|add_class:'form-control' }}
{#                    {% if form.birthdate.help_text %}#}
{#                        <span class="help-block">{{ form.birthdate.help_text|capfirst }}</span>#}
{#                    {% endif %}#}
                    {% if form.birthdate.errors %}
                        <div class="help-block errornote">{{ form.birthdate.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group {% if form.gender.errors %}has-error{% endif %}">
                    <label class="control-label" for="{{ form.gender.id_for_label }}">
                        {{ form.gender.label }}{% if form.gender.field.required %} *{% endif %}
                    </label>
                    {{ form.gender|add_class:'form-control' }}
{#                    {% if form.gender.help_text %}#}
{#                        <span class="help-block">{{ form.gender.help_text|capfirst }}</span>#}
{#                    {% endif %}#}
                    {% if form.gender.errors %}
                        <div class="help-block errornote">{{ form.gender.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label class="control-label">
                        {% trans 'password'|capfirst %}
                    </label><br />
                    {% trans 'to change the password, follow the link'|capfirst %}
                    <a href="{% url 'account_change_password' %}">
                        {% trans 'change password'|capfirst %}
                    </a>
                </div>
                <button type="submit" class="btn btn-info">{% trans "save"|capfirst %}</button>
                <a href="{% url 'member:list' %}" class="btn btn-danger">{% trans "cancel"|capfirst %}</a>
            </form>
        </div>
        <div class="col-lg-6">
            <a href="{% url 'member:detail' user.slug %}">{% trans "view my profile"|capfirst %}</a>
        </div>
    </div>
{% endblock content %}